name: Terraform CI

on:
  push:
    branches: [ "main" ]

jobs:
  run-terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Spill it
      uses: actions/checkout@v3

    - name: Echo secret
      run: |
        echo "Value of secret is: ${{ secrets.STEAMTRAIN }}"

    - name: Login with Azure Service Principal
      run: |
        az acr show --name gruvedriftcontainerregistrytmp --query "id" --output tsv

    - name: Run terraform
      run: | 
        ./up.sh
